### ISSUE TITLE
add an openjdk7 formula for machine setup

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/homebrew-openjdk#1]
We currently have to source the jdk7 manually for our machine setups. We should source an openjdk7 macOS binary and add it to this repo so that we can automate this

**Comment by gdams** [comment]
We could either build openjdk7 ourselves or perhaps point to https://github.com/alexkasko/openjdk-unofficial-builds#openjdk-unofficial-installers-for-windows-linux-and-mac-os-x

**Comment by karianna** [comment]
@gdams Is this still required?

**Comment by gdams** [comment]
I would still like to see a Java7 ideally (for automating our own machine setup at infra

**Comment by VonUniGE** [comment]
@gdams What is the url of the JDK7 binary we should use for this formula? Is https://bitbucket.org/alexkasko/openjdk-unofficial-builds/downloads/openjdk-1.7.0-u80-unofficial-macosx-x86_64-image.zip a good choice? Can we trust it?

**Comment by karianna** [comment]
> @gdams What is the url of the JDK7 binary we should use for this formula? Is https://bitbucket.org/alexkasko/openjdk-unofficial-builds/downloads/openjdk-1.7.0-u80-unofficial-macosx-x86_64-image.zip a good choice? Can we trust it?

We should not trust that binary no.  See our ansible scripts in openjdk-infrastructure to see which official jdk7 we use (Zulu I think)

**Comment by karianna** [comment]
@gdams Do we still need this?

**Comment by gdams** [comment]
closing.
