### ISSUE TITLE
can't install openjdk10 

### ISSUE THREAD

**Issue by luxcn** [AdoptOpenJDK/homebrew-openjdk#10]
brew install adoptopenjdk-openjdk10                                                                     
==> Installing adoptopenjdk-openjdk10 from adoptopenjdk/openjdk
==> Downloading https://github.com/AdoptOpenJDK/openjdk10-releases/releases/download/201807101745/OpenJDK10_x64_Mac_201807101745.tar.gz

then i find the correct url  : https://github.com/AdoptOpenJDK/openjdk10-releases/releases/download/jdk-10.0.1+10/OpenJDK10_x64_Mac_201807101745.tar.gz

**Comment by karianna** [comment]
I recently changed the tag - might need to upgrade something here.
