### ISSUE TITLE
How to switch between multiple versions

### ISSUE THREAD

**Issue by dant3** [AdoptOpenJDK/homebrew-openjdk#111]
Hi,
Thanks for awesome project!
I have installed both openjdk8 and 11, how can I switch between them?

**Comment by VonUniGE** [comment]
Personally, I've added the following lines to my `~/.bash_profile`:
```
# Set java version
# https://www.kevinhooke.com/2017/10/05/switching-java-versions-on-mac-os/
alias j11="export JAVA_HOME=`/usr/libexec/java_home -v 11`"
alias j8="export JAVA_HOME=`/usr/libexec/java_home -v 1.8`"
j8
```
My default jdk is jdk8. When I want to use jdk11, I type `j11` and I can come back to jdk8 with `j8`.

Read https://www.kevinhooke.com/2017/10/05/switching-java-versions-on-mac-os/ for details.

**Comment by SPConrad** [comment]
It would be really great if this was part of the readme.

**Comment by karianna** [comment]
> It would be really great if this was part of the readme.

@SPConrad - Can you submit a PR for that?

**Comment by shireeshaBongarala** [comment]
@karianna Raised a PR. Could you please review https://github.com/AdoptOpenJDK/homebrew-openjdk/pull/314 ?
Thank you!

**Comment by malanb5** [comment]
https://github.com/AdoptOpenJDK/homebrew-openjdk

> Personally, I've added the following lines to my `~/.bash_profile`:
> 
> ```
> # Set java version
> # https://www.kevinhooke.com/2017/10/05/switching-java-versions-on-mac-os/
> alias j11="export JAVA_HOME=`/usr/libexec/java_home -v 11`"
> alias j8="export JAVA_HOME=`/usr/libexec/java_home -v 1.8`"
> j8
> ```
> 
> My default jdk is jdk8. When I want to use jdk11, I type `j11` and I can come back to jdk8 with `j8`.
> 
> Read https://www.kevinhooke.com/2017/10/05/switching-java-versions-on-mac-os/ for details.

More programmatically from the AdoptOpenJDK repository:

jdk() {
        version=$1
        export JAVA_HOME=$(/usr/libexec/java_home -v"$version");
        java -version
 }

**Comment by arunsval** [comment]
After upgrading to openjdk version "14.0.1" 2020-04-14. above alias is not working

**Comment by aahlenst** [comment]
@arunsval Please open a new issue, explain what you did, what the desired outcome was and what the actual outcome is. Show the full output of your comand line.
