### ISSUE TITLE
How to Uninstall

### ISSUE THREAD

**Issue by iamMehedi** [AdoptOpenJDK/homebrew-openjdk#12]
I have installed using 
```
brew tap AdoptOpenJDK/openjdk
brew install adoptopenjdk-openjdk8
```

It seems to have overwritten the existing java installations. How do I uninstall?

**Comment by rahulpopuri** [comment]
+1, Did you figure out how to uninstall?

**Comment by karianna** [comment]
https://blog.adoptopenjdk.net/2018/10/macos-binary-changes - we're moving to casks

**Comment by gdams** [comment]
The new casks that I am writing will be much better and uninstalling will work in the same way as the other casks.

**Comment by rowena22323** [comment]
brew cask list
brew remove 'filename'
