### ISSUE TITLE
LTS cask

### ISSUE THREAD

**Issue by woj-tek** [AdoptOpenJDK/homebrew-openjdk#125]
It would be great to have cask following LTS releases, i.e.: `adoptopenjdk` which would install jdk11, jdk17, jdk23 when they are released.

**Comment by aahlenst** [comment]
@woj-tek We have multiple LTS releases. JDK 8 will stick around until 2030, so for the next 10 years there will be at least 2 active LTS releases. I'm not keen on adding additional aliases that aren't self-explanatory.
