### ISSUE TITLE
Missing (or Invalid?) Certs in openjdk10

### ISSUE THREAD

**Issue by MitchellMcKenna** [AdoptOpenJDK/homebrew-openjdk#128]
Once i got openjdk10 to install #126 
I would get the following SSL Error on run:
`javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

I noticed on StackOverflow this person was able to fix it by copying over the certs from jdk8: https://stackoverflow.com/questions/53246399/jdk8-jdk10-pkix-path-building-failed-suncertpathbuilderexception-unable-to

This is likely the same issue mentioned here in oracle/graal where they did the same thing (copy certs from jdk 8): https://github.com/oracle/graal/issues/378#issuecomment-384245987

**Comment by VonUniGE** [comment]
[According to Oracle](https://www.oracle.com/technetwork/java/javase/downloads/jdk10-downloads-4416644.html):

>  Java SE 10 has reached end of support. Users of Java SE 10 should switch to Java SE 11.

Java SE 10 is also a [non-LTS](https://www.oracle.com/technetwork/java/java-se-support-roadmap.html) release. Is there an interest to keep this issue open ?

**Comment by karianna** [comment]
We won't be re-releasing no.
