### ISSUE TITLE
jmods/*.jmod are broken in homebrew java11 install

### ISSUE THREAD

**Issue by kevinawalsh** [AdoptOpenJDK/homebrew-openjdk#167]
After doing "brew cask install adoptopenjdk11", I found that jlink fails with a hash mismatch. Some digging reveals that within the installed jmods directory, all of the .jmod files appear to have been unzipped-then-rezipped, breaking the sha256 hash references contained within them.

For example, within Contents/Home/jmods:
```
$ jmod describe java.base.jmod | grep "hashes java.xml "
hashes java.xml SHA-256 929bfb518525ecbf6f8cae090a934a1281e766953aa7556770c1373a5b44712f
$ sha256sum java.xml.jmod 
7a5c784efc2c4d0bd8471b376c72f4817bb2098c9cc3fd8ce96e4aa2f70d4871
```

Clearly, these hashes do not match. The same hash-mismatch happens for all of the jmod files.

The same hash-mismatch is present in the raw pkg files on github, so it isn't a post-installation issue.

If I instead download a plain tar.gz directly from github, rather than using homebrew or the pkg files, the hashes for that java.xml.jmod file will match, both showing value 21d97155832d8dc63f88bbf3589aeaa19ba2310243b1016646853b36fb98be1e 

A binary compare shows that the good and bad java.xml.jmod files are very different, except for the first few header bytes. But if I unzip them both, they both contain identical contents, and the only difference appears to be in the zip archive itself. The bad jmod files have internal zip timestamps of 19-Aug-05, with unx filesystem type, and zip entries for directories. The good jmod files have internal zip timestamps of 19-Jul-18, with fat filesystem type, and no zip entries for directories. The number and sizes of all the contained files are identical.

**Comment by karianna** [comment]
@gdams Is this another manifestation of the signing/notarization issue?

**Comment by gdams** [comment]
ahh yes! this explains the test failures that people were seeing. Because we codesign the jmods the checksums change, we need to find where the checksums are stored and update them post signing

**Comment by gdams** [comment]
we will get this fixed ASAP

**Comment by gdams** [comment]
this is fixed in openjdk-build, closing
