### ISSUE TITLE
Would it be possible to add something in the README about the difference between large heap and non-large heap binaries? I'm a little confused about whether this issue effects anything besides launching Eclipse.

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/homebrew-openjdk#168]
Would it be possible to add something in the README about the difference between large heap and non-large heap binaries? I'm a little confused about whether this issue effects anything besides launching Eclipse.

_Originally posted by @timgilbert in https://github.com/AdoptOpenJDK/homebrew-openjdk/issues/87#issuecomment-520961331_

**Comment by chase9** [comment]
Hi @karianna, it appears this was solved in 5dfc2d5.
