### ISSUE TITLE
add Open JDK 11 

### ISSUE THREAD

**Issue by apatrida** [AdoptOpenJDK/homebrew-openjdk#17]

**Comment by karianna** [comment]
Once we have a release version we can add this.

**Comment by apatrida** [comment]
@karianna like this? http://jdk.java.net/11/

**Comment by apatrida** [comment]
The official GA release is there with .tar.gz for Mac OSX

**Comment by karianna** [comment]
We need the AdoptOpenJDK release

**Comment by apatrida** [comment]
Ah, ok, understand now.

**Comment by iwan41** [comment]
Hi, 
https://github.com/AdoptOpenJDK/homebrew-openjdk/pull/21

adding new adoptopenjdk build to homebrew.
