### ISSUE TITLE
Tell users how to configure their $HOME/.bashrc ?

### ISSUE THREAD

**Issue by joeblew99** [AdoptOpenJDK/homebrew-openjdk#176]
Took me a while to work this out.

Mine ended up being:
/Library/Java/JavaVirtualMachines/adoptopenjdk-12.0.2.jdk//Contents/Home

Maybe it should echo this after running the install via brew ?

**Comment by polarapfel** [comment]
I'm using this on Mac OS X:

`export JAVA_HOME=$(/usr/libexec/java_home)`

After installing openjdk through brew using, it'll adapt the value to the newly installed Java version each time without a need to edit anything. You need to end your session and start a new one for the value to update, or source the file in BASH that does the export of the variable.

**Comment by gdams** [comment]
closing as @polarapfel's answer seems acceptable

**Comment by wellavelino** [comment]
Would it be possible to print out the path? 
similar to:

https://github.com/Homebrew/homebrew-cask/blob/master/Casks/java.rb
