### ISSUE TITLE
JDK 13 ETA

### ISSUE THREAD

**Issue by adityasrini** [AdoptOpenJDK/homebrew-openjdk#177]
Is there an ETA for when JDK 13 and possibly JDK 14 will be out?

**Comment by karianna** [comment]
Hoping sometime next week

**Comment by TrueHeresy** [comment]
Does/will this include an option for the OpenJ9 version of JDK 13?

**Comment by karianna** [comment]
> Does/will this include an option for the OpenJ9 version of JDK 13?

This is done.

**Comment by adityasrini** [comment]
Hi what's the progress on this? I'm no longer able to use adoptopenjdk's 12 from sdkman (codeship needs me to go through sdkman). This breaks dev and CI parity. Can this ticket be pushed up in priority? I'm sure there are others that would like to use home brew with adoptopenjdk's jdk 13.

**Comment by jhult** [comment]
@TrueHeresy, I believe the answer is it will include OpenJ9 (but I'm not 100% sure). I'd certainly like it to.

**Comment by gdams** [comment]
pull requests are in, sorry for the delay!
