### ISSUE TITLE
Bad link in adoptopenjdk11 cask?

### ISSUE THREAD

**Issue by stranljip** [AdoptOpenJDK/homebrew-openjdk#201]
If I try to install/update adoptopenjdk11 (11.0.5), I get a 404 on the following URL:
`https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/11.0.5%2B10/OpenJDK11(...)`

If I download from the website, I get another link:
`https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.5%2B10/OpenJDK11(...)`

It seems, that the part `download/11.0.5%2B10/OpenJDK11(...)` has changed to `download/jdk-11.0.5%2B10/OpenJDK11(...)`

**Comment by karianna** [comment]
@stranljip Can you try again? - I think we were in a 1/2 way house when you tried.

**Comment by stranljip** [comment]
Uitstekend! Works as expected, thank you for the notice.
