### ISSUE TITLE
back in time : adoptopenjdk8 (8,232:b09) != 8,222:b10

### ISSUE THREAD

**Issue by YannMoisan** [AdoptOpenJDK/homebrew-openjdk#202]
Due to the result of the following command :

```
$ brew cask outdated
adoptopenjdk8 (8,232:b09) != 8,222:b10
```

`brew cask upgrade` has installed an older version of `adoptopenjdk8`

**Comment by gdams** [comment]
hmm this is a weird one, I'm trying to investigate why that happened, we did switch to semver versioning. If you uninstall and reinstall what version do you get?

**Comment by gdams** [comment]
this is fixed
