### ISSUE TITLE
openjdk 13.0 installation error

### ISSUE THREAD

**Issue by hidvegin** [AdoptOpenJDK/homebrew-openjdk#265]
I tried update my openjdk 1.8.0 to the new openjdk package from linuxbrew, but I got this error. How can I resolve this?

`==> Upgrading 1 outdated package:
openjdk 1.8.0-212 -> 13.0.1+9
==> Upgrading openjdk 
==> Downloading https://hg.openjdk.java.net/jdk-updates/jdk13u/archive/jdk-13.0.
Already downloaded: /home/hidvegi/.cache/Homebrew/downloads/1d269c3494918f742ce34065ae326d878d3a39f988b064249f58cbac0b7a67ac--jdk13u-jdk-13.0.1+9.tar.bz2
==> Downloading https://download.java.net/java/GA/jdk12.0.2/e482c34c86bd4bf8b56c
Already downloaded: /home/hidvegi/.cache/Homebrew/downloads/0c063c1db55c4b1323810e59dca242bbd1bedc828894003511e13362cc81291b--openjdk-12.0.2_osx-x64_bin.tar.gz
==> ./configure --without-version-pre --without-version-opt --with-version-build
Last 15 lines from /home/hidvegi/.cache/Homebrew/Logs/openjdk/01.configure:
checking pkg-config is at least version 0.9.0... yes
checking for default LOG value... 
checking headless only... no
checking for graphviz dot... no, cannot generate full docs
checking for pandoc... no, cannot generate full docs
checking full docs... no, missing dependencies
checking for cacerts file... default
checking for jni library path... default
checking if packaged modules are kept... yes (default)
checking for version string... 13.0.1+9
configure: Found potential Boot JDK using configure arguments
configure: Potential Boot JDK found at /tmp/openjdk-20191117-20136-1ltcy8u/jdk13u-jdk-13.0.1+9/boot-jdk/Contents/Home is incorrect JDK version (/tmp/openjdk-20191117-20136-1ltcy8u/jdk13u-jdk-13.0.1+9/build/.configure-support/generated-configure.sh: line 29699: /tmp/openjdk-20191117-20136-1ltcy8u/jdk13u-jdk-13.0.1+9/boot-jdk/Contents/Home/bin/java: cannot execute binary file: Exec format error); ignoring
configure: (Your Boot JDK version must be one of: 12 13)
configure: error: The path given by --with-boot-jdk does not contain a valid Boot JDK
configure exiting with result code 1

READ THIS: https://docs.brew.sh/Troubleshooting

These open issues may also help:
openjdk@12: Build a bottle for Linux https://github.com/Homebrew/linuxbrew-core/pull/17223
openjdk: Build a bottle for Linux https://github.com/Homebrew/linuxbrew-core/pull/17073
openjdk@11: Build a bottle for Linux https://github.com/Homebrew/linuxbrew-core/pull/17074`

**Comment by aahlenst** [comment]
Our Homebrew packages are only for macOS. Linuxbrew apparently tries to compile the OpenJDK from source. This requires Java to succeed (see message about a boot JDK). You do not have a JAVA_HOME environment variable pointing to an installed JDK 12 or 13, hence the error.

I guess you do not want to compile from source. We have binary releases at https://www.adoptopenjdk.net/ and Linux packages at https://adoptopenjdk.net/installation.html#linux-pkg.
