### ISSUE TITLE
Unsigned error when using this cask on Catalina 10.15.1

### ISSUE THREAD

**Issue by excalbian** [AdoptOpenJDK/homebrew-openjdk#267]
After installing with `brew cask install adoptopenjdk` homebrew reported `🍺  adoptopenjdk was successfully installed!` but running `java --version` just gives this error:

<img width="421" alt="image" src="https://user-images.githubusercontent.com/242196/69514832-446c5600-0f12-11ea-9e47-3b8d027b1b01.png">

I found that this can be resolved by using `xattr -d com.apple.quarantine /Library/Java/JavaVirtualMachines/adoptopenjdk-13.0.1.jdk` (removing the quarantine attribute). Afterwards, the output is as expected:
```
~ java --version
openjdk 13.0.1 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 13.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 13.0.1+9, mixed mode, sharing)
```

Can the `xattr -d` command be added to the cask / package?

**Comment by gdams** [comment]
This is to do with the fact that the upstream cask (`adoptopenjdk`) uses the tar.gz rather than the notarized pkg. Consider using adoptopenjdk13. I will try and get the upstream folks to switch to using the pkg.

**Comment by henrik242** [comment]
Is this related? https://github.com/AdoptOpenJDK/homebrew-openjdk/issues/290

**Comment by winwisely99** [comment]
any movement on this ?

**Comment by winwisely99** [comment]
@gdams 

work around is to do this ?
````
brew cask install adoptopenjdk13

````

**Comment by Great-Li-Xin** [comment]
Same Issue Here

<img width="532" alt="Screen Shot 2019-12-17 at 11 29 33 AM" src="https://user-images.githubusercontent.com/17794470/70962534-8ecf9580-20c0-11ea-81f0-d1b676603fa3.png">

```
openjdk 13.0.1 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 13.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 13.0.1+9, mixed mode, sharing)
```

**Comment by Istuk** [comment]
I get this for `brew cask install adoptopenjdk13`
`Error: Cask 'adoptopenjdk13' is unavailable: No Cask with this name exists.`

Any idea how could this be resolved?

**Comment by gdams** [comment]
@Istuk have you run:

`brew tap AdoptOpenJDK/openjdk`?

**Comment by amit17051980** [comment]
For Eclipse-JEE
`brew cask install oracle-jdk`

**Comment by stephenwade** [comment]
You can also install the cask from Homebrew with the `--no-quarantine` option:

`brew cask install adoptopenjdk --no-quarantine`

**Comment by dva** [comment]
Open MacOS "System Preferences" -> "Security & Privacy" -> "General" and click **Allow** at the bottom for **adoptopenjdk-13.0.1.jdk**

**Comment by nimritee** [comment]
You just need to navigate to System Preferences (Settings) -> Security and Privacy -> Click all access.

**Comment by apiology** [comment]
If you're using a `Brewfile` (with `brew bundle`), you can use:

```
cask_args "no-quarantine": true
cask "adoptopenjdk"
```

**Comment by modelearth** [comment]
> brew cask install adoptopenjdk13

That worked - but only after installing and uninstalling Java from Oracle's java.com.

**Comment by aahlenst** [comment]
Fixed via https://github.com/Homebrew/homebrew-cask/pull/73145.
