### ISSUE TITLE
Invalid code signature in adoptopenjdk12

### ISSUE THREAD

**Issue by henrik242** [AdoptOpenJDK/homebrew-openjdk#290]
I managed to get a weird error in the latest `adoptopenjdk12` package on macOS Catalina.  It disappeared when I switched to the `openjdk@12` package:
```
Caused by: java.lang.UnsatisfiedLinkError: /private/var/folders/v5/3yprctcn47zdgnd_sj_3vy25cmgtv1/T/libjunixsocket-native-2.0.414387133462679574364.dylib: dlopen(/private/var/folders/v5/3yprctcn47zdgnd_sj_3vy25cmgtv1/T/libjunixsocket-native-2.0.414387133462679574364.dylib, 1): no suitable image found.  Did find:
    /private/var/folders/v5/3yprctcn47zdgnd_sj_3vy25cmgtv1/T/libjunixsocket-native-2.0.414387133462679574364.dylib: code signature in (/private/var/folders/v5/3yprctcn47zdgnd_sj_3vy25cmgtv1/T/libjunixsocket-native-2.0.414387133462679574364.dylib) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
    at org.newsclub.net.unix.NarSystem.loadLibrary(NarSystem.java:39)
```

**Comment by henrik242** [comment]
Happens with `adoptopenjdk13` as well

**Comment by henrik242** [comment]
Same thing in macOS Mojave

**Comment by henrik242** [comment]
Still seing the same thing

**Comment by karianna** [comment]
I don't believe the 12 series was properly notarized, as 12 is no longer supported we'll have to look at correcting this for 13.  

@gdams are the 13.0.2's notarized or do we need to respin those?

**Comment by henrik242** [comment]
If you are not planning to do a proper release you should probably just remove the adoptopenjdk12 package from Homebrew. It will fail for anyone trying to use it.

**Comment by aahlenst** [comment]
`$ xattr -d com.apple.quarantine /path/to/jdk` removes the quarantine bit if you need AdoptOpenJDK 12.
