### ISSUE TITLE
Overwrites Oracle Java Setup

### ISSUE THREAD

**Issue by AlexanderWillner** [AdoptOpenJDK/homebrew-openjdk#3]
Workflow:
1. ```brew cask install java```
2. ```brew install adoptopenjdk-openjdk10```
3. ```brew cask reinstall java```

Expected:
1. Oracle Java
2. Warning that java is already installed 
3. Oracle Java

Instead:
1. Oracle Java
2. OpenJDK
3. OpenJDK

**Comment by gdams** [comment]
Hmm this is a difficult one. If we were following the default behavior of `apt get` and the likes then each version would overwrite the previous version. In the short term, you could try adding `--no-link` to the command as this won't setup the symlinks.

**Comment by karianna** [comment]
https://blog.adoptopenjdk.net/2018/10/macos-binary-changes - the new layout will resolve this.
