### ISSUE TITLE
adoptopenjdk-openjdk11 not set as system java on macOS 10.13.6

### ISSUE THREAD

**Issue by maveric0815** [AdoptOpenJDK/homebrew-openjdk#31]
I installed adoptopenjdk-openjdk 11 via homebrew today on macOS 10.13.6. It installed fine but a linking error occured for which I filed a seperate issue.
This is issue is about adoptopenjdopenjdk11 not beeing recognized via /usr/libexec/java_home -V which is unfortunate since a lot of java apps on mac check this path for java and won't launch. You still need a workaround like the one described here [https://gist.github.com/chaines27/7f9a91237e79e6b4b28899b96d74986f](url).

**Comment by karianna** [comment]
See https://github.com/Homebrew/homebrew-cask/pull/52874 where this will be resolved in the next day or two.
