### ISSUE TITLE
adoptopenjdk.jdk does not work on mac

### ISSUE THREAD

**Issue by jomach** [AdoptOpenJDK/homebrew-openjdk#329]
I think that the moving step is not working and it create a file instead of folder. 

==> Downloading https://github.com/AdoptOpenJDK/openjdk14-binaries/releases/download/jdk-14%2B36/OpenJDK14U-jdk_x64_mac_hotspot_14_36.tar.gz
Already downloaded: /Users/jorge/Library/Caches/Homebrew/downloads/236c2ded56bf407c038243b22b654e3d38e65ce07055ec61ee958585375e26a1--OpenJDK14U-jdk_x64_mac_hotspot_14_36.tar.gz
==> Verifying SHA-256 checksum for Cask 'adoptopenjdk'.
==> Uninstalling Cask adoptopenjdk
==> Backing Generic Artifact 'adoptopenjdk-14.jdk' up to '/usr/local/Caskroom/adoptopenjdk/14,36/jdk-14+36'.
==> Removing Generic Artifact '/Library/Java/JavaVirtualMachines/adoptopenjdk-14.jdk'.
==> Purging files for version 14,36 of Cask adoptopenjdk
==> Installing Cask adoptopenjdk
==> Moving Generic Artifact 'jdk-14+36' to '/Library/Java/JavaVirtualMachines/adoptopenjdk-14.jdk'.
🍺  adoptopenjdk was successfully installed!

I installed now 13 and it works.

**Comment by furritos** [comment]
To add a little bit more to this issue, I did get this pop up:

![image](https://user-images.githubusercontent.com/2133717/77363470-04767d80-6d10-11ea-90c5-8629d3156a3b.png)

**Comment by furritos** [comment]
One more bit of good news, got it working.  

It seems that macOS (I guess it might be Catalina but that's all I have for now) doesn't like the `.jdk` as part of the directory name.  Removing `.jdk` from `/Library/Java/JavaVirtualMachines/adoptopenjdk-14.jdk`allows it to work.

The second issue is from macOS security preventing you from opening "`classes.jsa`" but that can be fixed by going to **System & Preferences** ==> **General** and clicking on the "`allow`" button.

**Comment by gdams** [comment]
@furritos this is because you're using the upstream `adoptopenjdk` cask which uses the tarball, I've requested that they switch to our notarized installers multiple times.

please try:

```bash
brew tap AdoptOpenJDK/openjdk
brew cask install adoptopenjdk14
```

**Comment by cfedak** [comment]
Removing my existing  adoptopenjdk cask and following @gdams 's suggestion resolved a similar issue for me after upgrading macOS to 10.15.4.  Thank you!

**Comment by karianna** [comment]
Will keep this open until upstream accepts our patch

**Comment by matthew-manuel** [comment]
> Removing my existing adoptopenjdk cask and following @gdams 's suggestion resolved a similar issue for me after upgrading macOS to 10.15.4. Thank you!

Yes, I also had to delete the existing `adoptopenjdk-14.jdk` "Package", and then reinstall as per @gdams ' suggestion, reinstall without deleting still left macOS treating the directory as a "Package" file.

**Comment by aahlenst** [comment]
Fixed via https://github.com/Homebrew/homebrew-cask/pull/73145.

**Comment by virajkanwade** [comment]
Just putting it here in case somebody else faces the same:

`mv jdk-11.0.8+10 jdk-11.0.8-10 `

what fixed it for me
