### ISSUE TITLE
installation of adoptopenjdk 11 and 14 does not work with Eclipse based applications

### ISSUE THREAD

**Issue by dashorst** [AdoptOpenJDK/homebrew-openjdk#331]
Eclipse based applications try to use the macOS Java reconsiliation process for starting their internal Java. With openjdk installed through the adoptopenjdk casks this fails, whereas using the zulu based openjdk casks does work.

A little investigation shows that adoptopenjdk distributions of openjdk create `Contents/MacOS/libjli.dylib` whereas the zulu based distributions make that a symbolic link to `Contents/Home/lib/jli/libjli.dylib`.

Modifying the adoptopenjdk install such that the `Contents/MacOS/libjli.dylib` becomes a symbolic link to `Contents/Home/lib/jli/libjli.dylib` makes the adopt openjdk distribution work as normal.

My guess is that the starter of Eclipse is unable to find the other necessary libraries when loading the libjli.dylib from Contents/MacOS.

Please consider updating the installer to use a symbolic link instead of the current way of packing libjli.dylib.

I've not used other versions of AdoptOpenjdk brew casks but I suppose they use the same packaging and installation and have the same issue.

**Comment by gdams** [comment]
@dashorst the new release should resolve this. Can you please confirm?

**Comment by dashorst** [comment]
Unfortunately it didn't work out of the box, but that was because I think Eclipse uses the adoptopenjdk14 installation rather than the 11 version. 

When I modified the Info.plist to point to adoptopenjdk11 homebrew installation, Eclipse started just fine. When I modified it to point to the adoptopenjdk14 homebrew installation, Eclipse fails to start with the alert popup "Failed to create the Java Virtual Machine"

```
$ java -version
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)
```

So what you did for 11.0.7 is great. 👍

**Comment by gdams** [comment]
@dashorst which adoptopenjdk14 version are you using?

**Comment by dashorst** [comment]
```
openjdk version "14" 2020-03-17
OpenJDK Runtime Environment AdoptOpenJDK (build 14+36)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14+36, mixed mode, sharing)
```

**Comment by gdams** [comment]
@dashorst we've released a new jdk14 since then. Try `brew cask upgrade adoptopenjdk14`

**Comment by dashorst** [comment]
It was weird, as I did do a `brew cask upgrade`, which updated a lot of packages, including adoptopenjdk11, but apparently not adoptopenjdk14...

Manually upgrading did the trick.
