### ISSUE TITLE
Cask with Openjdk9 doesn't work

### ISSUE THREAD

**Issue by vadim-hleif** [AdoptOpenJDK/homebrew-openjdk#35]
## what
* Fix command `brew install adoptopenjdk-openjdk9`

![image](https://user-images.githubusercontent.com/11632146/46671892-ac60bf80-cbde-11e8-8108-39a6f068ba45.png)

## why
* It doesn't work
* Other versions works fine

**Comment by karianna** [comment]
@vadim-hleif - This has been fixed.
