### ISSUE TITLE
Support OpenJDK 11

### ISSUE THREAD

**Issue by marcottedan** [AdoptOpenJDK/homebrew-openjdk#38]
Is there any way to support Java 11 in the future? It's available here: https://solarianprogrammer.com/2018/09/28/installing-openjdk-macos/

Since the Server Licensing change in Oracle JDK 11, it become increasingly urgent to migrate to Open JDK 11.

Thank you!

**Comment by karianna** [comment]
11 Support is currently over at Homebrew core, but there's a discussion going on there as to whether it needs to come back here.   Hopefully have an answer soon!

**Comment by gdams** [comment]
jdk 11 hotspot added to cask

**Comment by bentito** [comment]
> 11 Support is currently over at Homebrew core, but there's a discussion going on there as to whether it needs to come back here. Hopefully have an answer soon!

What does that mean? Could you supply a command link like `brew install ???` because `Error: Cask 'adoptopenjdk11' is unavailable: No Cask with this name exists.` when I run `brew cask install adoptopenjdk11` as per your own readme.md.

**Comment by bentito** [comment]
Well to answer my own question in case anyone looks at this closed issue:
```
$ brew cask info java
java: 11.0.1,13
https://jdk.java.net/
/usr/local/Caskroom/java/9.0.1,11 (383.0MB)
From: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/java.rb
==> Name
OpenJDK
==> Artifacts
```
And so the correct command to install Java 11 at this moment at least (Dec 20, 2018) is:
`$ brew cask reinstall java`
