### ISSUE TITLE
Improve homebrew support

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/homebrew-openjdk#4]
Workflow:
```brew cask install openjdK```

Expected:
Works analog to ```brew cask install java```

Instead:
No official cask.

Further Information:
- Implementation started at https://github.com/AdoptOpenJDK/homebrew-openjdk - however, not as a ```cask``` and not included into the [main branch](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request)
- Brew: https://brew.sh
- Formulas: http://brewformulas.org
- Discussion on how to install OpenJDK: https://discourse.brew.sh/t/how-to-install-openjdk-with-brew/712

**Comment by gdams** [comment]
Casks seem to be for the installation of large `.app` files which we aren't doing. I personally think that using `brew` is fine for this. 

As for the question about merging into the main branch..... I'm open to this concept **but** I do like the way that with this current setup we can simply manage our own repo and cut releases immediately without having to get someone to manually merge our pull request into the main repo. I'd be happy to add a pull request and see how it goes down in the main repo though.

**Comment by AlexanderWillner** [comment]
Given that [Oracle Java is a cask](https://github.com/caskroom/homebrew-cask/blob/master/Casks/java.rb) my assumption is that OpenJDK should also be a cask. This will probably be discussed after creating a [Homebrew Pull Request](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request). Maintaining also an own [Tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md) to update immediately w/o waiting for the pull request to be merged, might be another option.

Anyway, waiting for JCK compliance and offering a Tap in the mean time might be the safest option.

**Comment by gdams** [comment]
closing as the using brew appears to be okay for now

**Comment by moshen** [comment]
While this is a little bit of issue necromancy, after checking out this Tap I think the best course would be to implement as Casks.

- Casks aren't only for `.app`s, they are also for software that is installed globally or requires admin permissions to install
- @gdams [zulu](https://github.com/Homebrew/homebrew-cask/blob/3ca5556706a8e08fca9ea35bc82e9645494ebb05/Casks/zulu.rb) and [java](https://github.com/Homebrew/homebrew-cask/blob/3ca5556706a8e08fca9ea35bc82e9645494ebb05/Casks/java.rb) (Now openjdk) are both Casks and both simply install into `/Library/Java/JavaVirtualMachines/`
- Installing into `/usr/local` does not allow GUI apps to use the installed jvm (as far as I know)
- @gibfahn , unlike linux (and other nixs) Mac Java installs in various JavaVirtualMachines folders are usable on the cli through the `/usr/libexec/java_home` utility, which also allows you to switch jvms
- @gibfahn buo/brew-cask-upgrade is completely unnecessary, use either `brew cask upgrade caskname` or `brew cask reinstall caskname`

I would be happy to make a PR converting these to Casks.

Maybe it would be better just to contribute these to https://github.com/Homebrew/homebrew-cask-versions.

**Comment by gdams** [comment]
@moshen I've just started hacking together a basic cask file. I'll update the issue with progress

**Comment by moshen** [comment]
@gdams 👍 nice, seems like you basically want something like the openjdk one: https://github.com/Homebrew/homebrew-cask/blob/3ca5556706a8e08fca9ea35bc82e9645494ebb05/Casks/java.rb

**Comment by gdams** [comment]
nearly finished now, just getting the plist stuff done :)

**Comment by gdams** [comment]
Okay so this cask file seems to be passing all of the tests and installing Java in the correct location. I'm pretty happy with this other than the fact that I curl the `Info.plist` file in from a gist right now. We should probably move these Info.plist files to an internal repo somewhere. Also the generated `Info.plist` might need a few other bits being changed (see below)

```plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>English</string>
	<key>CFBundleExecutable</key>
	<string>libjli.dylib</string>
	<key>CFBundleGetInfoString</key>
	<string>AdoptOpenJDK 1.8.0_172</string>
	<key>CFBundleIdentifier</key>
	<string>net.java.openjdk.1.8.0.jdk</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>7.0</string>
	<key>CFBundleName</key>
	<string>OpenJDK 1.8.0</string>
	<key>CFBundlePackageType</key>
	<string>BNDL</string>
	<key>CFBundleShortVersionString</key>
	<string>1.0</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleVersion</key>
	<string>10.0.2</string>
	<key>JavaVM</key>
	<dict>
		<key>JVMCapabilities</key>
		<array>
			<string>CommandLine</string>
		</array>
		<key>JVMMinimumFrameworkVersion</key>
		<string>13.2.9</string>
		<key>JVMMinimumSystemVersion</key>
		<string>10.6.0</string>
		<key>JVMPlatformVersion</key>
		<string>1.8</string>
		<key>JVMVendor</key>
		<string>Oracle Corporation</string>
		<key>JVMVersion</key>
		<string>1.8.0_172</string>
	</dict>
</dict>
</plist>
```

```ruby
cask 'adoptopenjdk8' do
  version '8u172-b11,1.8.0_172'
  sha256 'c271c5aeebfec5cd6f41c24092472a66fc55f893e3118e63f4c1ab1cb4446157'

  # github.com was verified as official when first introduced to the cask
  url "https://github.com/AdoptOpenJDK/openjdk8-releases/releases/download/jdk8u172-b11/OpenJDK8_x64_Mac_jdk#{version.before_comma}.tar.gz"
  appcast 'https://github.com/adoptopenjdk/openjdk8-releases/releases.atom'
  name 'AdoptOpenJDK8'
  homepage 'https://adoptopenjdk.net/'

  postflight do
    system_command '/bin/mv',
                   args: ['-f', '--', "/usr/local/Caskroom/adoptopenjdk8/#{version}/jdk#{version.before_comma}",
                          '/usr/local/Caskroom/adoptopenjdk8/']
    system_command '/bin/rm',
                   args: ['-rf', '--', "/usr/local/Caskroom/adoptopenjdk8/#{version}"]
    system_command '/bin/mkdir',
                   args: ['-p', '--', "/Library/Java/JavaVirtualMachines/adoptopenjdk-#{version.after_comma}.jdk/Contents/MacOS"],
                   sudo: true
    system_command '/bin/ln',
                   args: ['-s', '--', "/usr/local/Caskroom/adoptopenjdk8/jdk#{version.before_comma}",
                          "/Library/Java/JavaVirtualMachines/adoptopenjdk-#{version.after_comma}.jdk/Contents/Home"],
                   sudo: true
    system_command '/bin/ln',
                   args: ['-s', '--', "/usr/local/Caskroom/adoptopenjdk8/jdk#{version.before_comma}/jre/lib/jli/libjli.dylib",
                          "/Library/Java/JavaVirtualMachines/adoptopenjdk-#{version.after_comma}.jdk/Contents/MacOS/libjli.dylib"],
                   sudo: true
    system_command '/usr/bin/curl',
                   args: ['--output', "/Library/Java/JavaVirtualMachines/adoptopenjdk-#{version.after_comma}.jdk/Contents/Info.plist",
                          'https://gist.githubusercontent.com/chaines27/32810cdfddefeeb5965e2969eb709fb5/raw/5ae95952b91f879e849c2be8a3a90be2d54ea1ec/homebrew-openjdk-1.8-info.plist'],
                   sudo: true
    system_command '/usr/libexec/PlistBuddy',
                   args: ['-c', "Set :CFBundleGetInfoString AdoptOpenJDK #{version.after_comma}", "/Library/Java/JavaVirtualMachines/adoptopenjdk-#{version.after_comma}.jdk/Contents/Info.plist"],
                   sudo: true
  end

  uninstall_postflight do
    system_command '/bin/rm',
                   args: ['-rf', '--', "/usr/local/Caskroom/adoptopenjdk8/jdk#{version.before_comma}"]
    system_command '/bin/rm',
                   args: ['-rf', '--', "/Library/Java/JavaVirtualMachines/adoptopenjdk-#{version.after_comma}.jdk"],
                   sudo: true
  end
end
```

**Comment by odrzutowiec** [comment]
hello i'd really appreciate ```brew install openjdk``` preferably with everything just magically working :)

**Comment by gdams** [comment]
here is the first PR for jdk11 https://github.com/Homebrew/homebrew-cask/pull/52874/
