### ISSUE TITLE
Unable to install adoptopenjdk12

### ISSUE THREAD

**Issue by johnthagen** [AdoptOpenJDK/homebrew-openjdk#419]
With the latest Homebrew and macOS 10.15.5, I am unable to install `adoptopenjdk12`.

```bash
% brew cask install adoptopenjdk12
Error: Cask 'adoptopenjdk12' is unavailable: No Cask with this name exists.
```

**Comment by karianna** [comment]
@johnthagen did you `brew tap AdoptOpenJDK/openjdk` first?

**Comment by johnthagen** [comment]
@karianna Ah, that was it thanks. Should that line be added before the **Latest** section in the README. It wasn't immediately clear to me as a new user that that was needed for the latest release.

**Comment by johnthagen** [comment]
Oh I see, the tap is only needed for *non*-latest version. I've submitted an upstream PR to `openapi-generator` to clarify their docs.
