### ISSUE TITLE
AdoptOpenJDK 8 libfontmanager.dylib requires libfreetype.6.dylib

### ISSUE THREAD

**Issue by rmartin7c** [AdoptOpenJDK/homebrew-openjdk#42]
When I attempted to run IntelliJ IDEA 2018.2 using Adopt OpenJDK 8 as the boot JDK, it failed with the following:

```
Caused by: java.lang.UnsatisfiedLinkError: /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/libfontmanager.dylib: dlopen(/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/libfontmanager.dylib, 1): Library not loaded: @rpath/libfreetype.6.dylib
  Referenced from: /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/libfontmanager.dylib
  Reason: image not found
```

I was able to recover by manually installing freetype from homebrew: `brew install freetype`

Can we solve this with a dependency on the cask(s)?

**Comment by karianna** [comment]
Which cask did you use for this?  It may actually be an underlying build problem we have with our Mac OS X binaries

**Comment by gdams** [comment]
Coretto had the same issue as us... we should apply the same fix: corretto/corretto-8#6

**Comment by 1stone** [comment]
Same problem here when using `adoptopenjdk8` with Tomcat8.
I can confirm that linking the library as @gdams suggested, does fix the problem.

**Comment by gdams** [comment]
@sxa555 / @johnoliver could we add this command to the build scripts?

**Comment by gdams** [comment]
@rmartin7c please try with the new jdk8 release?

**Comment by rmartin7c** [comment]
@gdams Looks good to me.
