### ISSUE TITLE
brew cask install adoptopenjdk8 - Error: No such file or directory - getcwd 

### ISSUE THREAD

**Issue by bradtumy** [AdoptOpenJDK/homebrew-openjdk#457]
brew tap AdoptOpenJDK/openjdk
Updating Homebrew...

brew cask install adoptopenjdk8
Updating Homebrew...
==> Downloading https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u265-b01/OpenJDK8U-jdk_x64_mac_hotspot_8u265b01.pkg
Already downloaded: /Users/btumy/Library/Caches/Homebrew/downloads/33a932bba3f6b57c6a06341ab08226a51233bca1b5832aed7461b78b013cb43d--OpenJDK8U-jdk_x64_mac_hotspot_8u265b01.pkg
==> Verifying SHA-256 checksum for Cask 'adoptopenjdk8'.
==> Installing Cask adoptopenjdk8
==> Running installer for adoptopenjdk8; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
Password:
installer: Package name is AdoptOpenJDK
installer: Installing at base path /
installer: The install was successful.
package-id: net.adoptopenjdk.8.jdk
version: 1.8.0_265-b01
volume: /
location: Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk
install-time: 1600112371
Error: No such file or directory - getcwd

**System**:
MacOS Catalina
10.15.5

brew -v
Homebrew 2.5.1
Homebrew/homebrew-core (git revision aadd; last commit 2020-09-14)
Homebrew/homebrew-cask (git revision b294f; last commit 2020-09-14)

**Comment by aahlenst** [comment]
Double-check that your shell's working directory exists. If you're typing commands in a directory that you've deleted (for example, through Finder), you get errors like that.

**Comment by bradtumy** [comment]
@aahlenst Thank you for a quick response.  That was exactly the issue.
