### ISSUE TITLE
Installing an older release from adoptopenjdk

### ISSUE THREAD

**Issue by wgwz** [AdoptOpenJDK/homebrew-openjdk#496]
Suppose you want to install an older version of adoptopenjdk using homebrew, i.e.:

https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/tag/jdk8u252-b09.1

Is there a clever way to do that via `brew cask install`?

i.e. I like having the `jdk` command:

```
jdk                        
java_home: option requires an argument -- v
openjdk version "1.8.0_272"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_272-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.272-b10, mixed mode)
```

Unfortunately the software I'm going to be developing on is not compatible with versions greater than 255.

```
Caused by: java.lang.IllegalArgumentException: Invalid version number: Version number may be negative or greater than 255
```

Here's some more diagnostics:

```
➜  tomcat-7.0.62 brew cask info adoptopenjdk/openjdk/adoptopenjdk8
adoptopenjdk8: 8,272:b10
https://adoptopenjdk.net/
/usr/local/Caskroom/adoptopenjdk8/8,272:b10 (100.6MB)
From: https://github.com/adoptopenjdk/homebrew-openjdk/blob/HEAD/Casks/adoptopenjdk8.rb
==> Name
AdoptOpenJDK 8
==> Description
AdoptOpenJDK OpenJDK (Java) Development Kit
==> Artifacts
OpenJDK8U-jdk_x64_mac_hotspot_8u272b10.pkg (Pkg)
➜  tomcat-7.0.62 
➜  tomcat-7.0.62 
➜  tomcat-7.0.62 java -version
openjdk version "1.8.0_272"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_272-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.272-b10, mixed mode)
```

Is there something like `brew cask install adoptopenjdk8@8,252`?

**Comment by aahlenst** [comment]
Homebrew does not really support this use case. If you need a specific version, download the PKG from our release archive: https://adoptopenjdk.net/archive.html?variant=openjdk8&jvmVariant=hotspot. It's installed to the default location, so you can activate it by setting `export JAVA_HOME=$(/usr/libexec/java_home -v1.8)`.

**Comment by wgwz** [comment]
It turned out that the cleanest way for me to do this was to dig through the git history and get a raw version of the adoptopenjdk8.rb cask, and install from the URL (it required reinstall because I previously had a newer version):

```
brew reinstall https://raw.githubusercontent.com/AdoptOpenJDK/homebrew-openjdk/130a5bbbde22c119d11d8a288b85d4bdd436887e/Casks/adoptopenjdk8.rb
```

I dug through the git history to find the specific version that I needed, here's history i.e.:

https://github.com/AdoptOpenJDK/homebrew-openjdk/commits/master/Casks/adoptopenjdk8.rb

By far cleaner than having to manually download a file, and deal with it that way. How it will be in terms of switching versions, I'm not quite sure. I imagine I can just reinstall when I need a new version again.

I guess this method could eventually break. But it works.

**Comment by wgwz** [comment]
For any other poor souls out there who might come across this while trying to run some older version of software, here's an update to my previous post. Most recently, that previous command failed for me:

```
$ brew reinstall https://raw.githubusercontent.com/AdoptOpenJDK/homebrew-openjdk/130a5bbbde22c119d11d8a288b85d4bdd436887e/Casks/adoptopenjdk8.rb                                                                                                                                                                           
Traceback (most recent call last): 'brew extract' or 'brew create' and 'brew tap-new' to create a formula file in a tap on GitHub instead.: Invalid usage: Non-checksummed download of adoptopenjdk8 formula file from an arbitrary URL is unsupported!  (UsageError) 'brew extract' or 'brew create' and 'brew tap-new' to create a formula file in a tap on GitHub instead.: Invalid usage: Non-checksummed download of adoptopenjdk8 formula file from an arbitrary URL is unsupported!  (UsageError)    
```

Instead I had to download the file and then reinstall from the local copy of the file:

```
$ wget wget https://raw.githubusercontent.com/AdoptOpenJDK/homebrew-openjdk/130a5bbbde22c119d11d8a288b85d4bdd436887e/Casks/adoptopenjdk8.rb
$ brew reinstall --cask adoptopenjdk8.rb
==> Downloading https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u252-b09.1/OpenJDK8U-jdk_x64_mac_hotspot_8u252b09.pkg
Already downloaded: /Users/kl3020/Library/Caches/Homebrew/downloads/57a6643f7b6de270e63dfc545e0d665dc6de2c7081f7537ffba2ccdbdae46d2d--OpenJDK8U-jdk_x64_mac_hotspot_8u252b09.pkg
==> Uninstalling Cask adoptopenjdk8
==> Uninstalling packages:
net.adoptopenjdk.8.jdk
Password:
==> Purging files for version 8,275:b01 of Cask adoptopenjdk8
==> Installing Cask adoptopenjdk8
==> Running installer for adoptopenjdk8; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
installer: Package name is AdoptOpenJDK
installer: Installing at base path /
installer: The install was successful.
package-id: net.adoptopenjdk.8.jdk
version: 1.8.0_252-b09
volume: /
location: Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk
install-time: 1611599625
🍺  adoptopenjdk8 was successfully installed!
```

Then activating JDK 1.8, you can see works successfully (using the old version I needed **1.8.0_252**):

```
$ jdk 1.8                                                                                                                             
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.252-b09, mixed mode)
```

Disclaimer: As with old versions of software, there are probably security risks here so do be careful.

**Comment by MikhailTymchukFT** [comment]
I've tried to install version 8,242:b08 of openjdk [as described at stackoverflow](https://stackoverflow.com/a/64125796/13380816), but brew cannot find this version:
```
$ brew tap-new AdoptOpenJDK/openjdk
$ brew extract --version 8,242:b08 adoptopenjdk8 AdoptOpenJDK/homebrew-openjdk
==> Searching repository history
Error: Could not find adoptopenjdk8! The formula or version may not have existed.
```

How to extract this specific version of a formula?

**Comment by abaxanean** [comment]
Thank you @wgwz !

**Comment by wgwz** [comment]
@MikhailTymchukFT I realize your comment was aeons ago in internet time but you can find what you were looking for by looking through the [commit history for the adoptopenjdk file](https://github.com/AdoptOpenJDK/homebrew-openjdk/commits/master/Casks/adoptopenjdk8.rb).

Once you do that you can find out the specific commit that introduced 8,242:b08, which in this case is "0336578702d597c5986820d11cfd27e63703a899".

From there you do these steps and it should work (notice the commit from above is in the URL):
```
$ wget https://raw.githubusercontent.com/AdoptOpenJDK/homebrew-openjdk/0336578702d597c5986820d11cfd27e63703a899/Casks/adoptopenjdk8.rb
$ brew reinstall --cask adoptopenjdk8.rb
$ jdk 1.8
```

Another disclaimer: This method works but I'm no professional Java developer. There is probably a better way :-)
