### ISSUE TITLE
Error while attempting to install the adoptopenjdk-openjdk9 formula

### ISSUE THREAD

**Issue by drakiula** [AdoptOpenJDK/homebrew-openjdk#5]
The download link seems to be broken.
> brew tap AdoptOpenJDK/openjdk
> brew install adoptopenjdk-openjdk9
Updating Homebrew...
==> Installing adoptopenjdk-openjdk9 from adoptopenjdk/openjdk
==> Downloading https://github.com/AdoptOpenJDK/openjdk9-releases/releases/download/jdk-9%2B181/OpenJDK9_x64_Mac_jdk-9.181.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "adoptopenjdk-openjdk9"
**Download failed: https://github.com/AdoptOpenJDK/openjdk9-releases/releases/download/jdk-9%2B181/OpenJDK9_x64_Mac_jdk-9.181.tar.gz**

**Comment by karianna** [comment]
Ah yes, we don't have this release presently.  This is being fixed over in `openjdk-build` https://github.com/AdoptOpenJDK/openjdk-build/issues/330

**Comment by karianna** [comment]
Fixed
