### ISSUE TITLE
Does installing openjdk via homebrew automatically set $JAVA_HOME for me?

### ISSUE THREAD

**Issue by ColtonIdle** [AdoptOpenJDK/homebrew-openjdk#501]
I was referred to homebrew-openjdk via this tweet https://twitter.com/JakeWharton/status/1263656692643921920 and it makes it seem like $JAVA_HOME gets set automatically?

**Comment by aahlenst** [comment]
No, that isn't what Jake implied. AdoptOpenJDK is installed into the standard location: `/Library/Java/JavaVirtualMachines/`. This makes AdoptOpenJDK discoverable via `/usr/libexec/java_home -v"vsersion"`. And you can automatically switch between versions per shell session by running `export JAVA_HOME=$(/usr/libexec/java_home -v"$version")`.

**Comment by ColtonIdle** [comment]
Thanks for the response. I guess I didn't understand two things
1. that there is a standard location
2. what `/usr/libexec/java_home -v"vsersion"` is

I know the docs include a snippet on JAVA_HOME, but it's under https://github.com/AdoptOpenJDK/homebrew-openjdk#switch-between-different-jdk-versions and I don't have any intention on switching between jdk versions.

Looks like my solution is that I will just add `export JAVA_HOME=$(/usr/libexec/java_home)` to my bash profile (leaving off the `-v"vsersion"`)

**Comment by ColtonIdle** [comment]
@aahlenst any chance you can take a look at my above comment? I'm just learning and so I'd appreciate it.

**Comment by aahlenst** [comment]
@ColtonIdle What's your question? I would have answered if I had recognized a question somewhere :smile:

**Comment by ColtonIdle** [comment]
@aahlenst =) Sorry about that.

My questions stem from understanding java standard location and setting my JAVA_HOME.
1. Just confirming that java/jdk has a standard "location"? i.e. /Library/Java/JavaVirtualMachines/
2. I want to add a JAVA_HOME to my machine to point to my jdk I installed. The docs include a snippet on JAVA_HOME, but it's under https://github.com/AdoptOpenJDK/homebrew-openjdk#switch-between-different-jdk-versions (but I DONT have any intention on switching between jdk versions)

Is `export JAVA_HOME=$(/usr/libexec/java_home)` to my bash profile (leaving off the -v"vsersion") the right thing to do? If so, I'm confused by why it's not `export JAVA_HOME=$( /Library/Java/JavaVirtualMachines/)`

**Comment by aahlenst** [comment]
> Just confirming that java/jdk has a standard "location"? i.e. `/Library/Java/JavaVirtualMachines/`

It's what `java_home` and friends expect, so I'd call it the standard location.

> I want to add a `JAVA_HOME` to my machine to point to my jdk I installed.

Run `export JAVA_HOME=$(/usr/libexec/java_home)` to set `JAVA_HOME`. If you don't set `JAVA_HOME`, running `java` should pick up the JDK you have installed anyway.

>  If so, I'm confused by why it's not export `JAVA_HOME=$( /Library/Java/JavaVirtualMachines/)` 

Because `JAVA_HOME` has to be something like `/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home`.

**Comment by ColtonIdle** [comment]
Aha. Okay. I guess I was confused by java_home and JAVA_HOME and why some programs just worked and why some didn't.

This was really helpful

>If you don't set JAVA_HOME, running java should pick up the JDK you have installed anyway. But there are programs that need JAVA_HOME.

Thank you. I learned something new today!
