### ISSUE TITLE
Installation not possible

### ISSUE THREAD

**Issue by dbathlon** [AdoptOpenJDK/homebrew-openjdk#512]
I have encountered a problem with the installation:

`brew install --cask adoptopenjdk-jre
==> Downloading https://github.com/AdoptOpenJDK/openjdk15-binaries/releases/down
Already downloaded: /Users/Denis/Library/Caches/Homebrew/downloads/d4445c76004358d1843a6f186b74d110e3ca15f3e5b437d8051b3db69e61c922--OpenJDK15U-jre_x64_mac_hotspot_15.0.1_9.pkg
==> Installing Cask adoptopenjdk-jre
==> Running installer for adoptopenjdk-jre; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are i
`
after this, nothing happens. I waited for 20 Mins. After I cancel with ctrl - c, this is shown:

^C==> Purging files for version 15.0.1,9.1 of Cask adoptopenjdk-jre
Error: Operation not permitted
Password:`

I repeated this several times, but nothing changed.

Is this a bug or an user error?

**Comment by aahlenst** [comment]
Usually neither but problems in macOS or Homebrew. The usual steps for diagnostics/repair:

* retry with `--force`.
* `brew update-reset && brew update` and retry.
* `brew doctor`, fix as many issues as possible, retry.

**Comment by dbathlon** [comment]
Hi,

thanks for your help. I tried it with --force and it worked.
