### ISSUE TITLE
adoptopenjdk8 $PATH

### ISSUE THREAD

**Issue by julienmiclo** [AdoptOpenJDK/homebrew-openjdk#518]
Hello,
i need to export java (adoptopenjdk8) in my $PATH for cordova, but i can't find where he is installed.
Can you tell me the correct path ?

Thank you !

macOS : 11.2.1
Homebrew : 3.0.1

**Comment by aahlenst** [comment]
A subdirectory of `/Library/Java/JavaVirtualMachines/`. If you need the `java` binary, it's in `/Library/Java/JavaVirtualMachines/<replace with JDK folder>/Contents/Home/bin`.
