### ISSUE TITLE
Provide native builds for M1 Apple Silicon (ARM) Macs in Homebrew

### ISSUE THREAD

**Issue by grahamrb** [AdoptOpenJDK/homebrew-openjdk#530]
AdoptOpenJDK now includes a build for the new M1-based (Apple Silicon) Macs. Ideally, the Homebrew package should provide this ARM based build when being installed on an Apple Silicon Mac rather than relying on Rosetta 2 to run the JDK.

Link to relevant AdoptOpenJDK ticket where ARM builds have been implemented: https://github.com/adoptium/temurin-build/issues/1922

Current output when running `brew install --cask adoptopenjdk ` on an M1 Mac without Rosetta 2 installed:

```
installer: This package requires Rosetta 2 to be installed.
                Please install Rosetta 2 and then try again.
                    `sudo softwareupdate --install-rosetta`

installer: Error - AdoptOpenJDK can’t be installed on this computer.
```

**Comment by gdams** [comment]
Please switch to using the temurin cask: https://adoptium.net/installation/
