### ISSUE TITLE
Do you wish to rename this formula to temurin?

### ISSUE THREAD

**Issue by mtgto** [AdoptOpenJDK/homebrew-openjdk#536]
Congrat, AdoptOpenJDK is now [adoptium](https://blog.adoptopenjdk.net/2020/06/adoptopenjdk-to-join-the-eclipse-foundation/).
I have watched https://github.com/Homebrew/homebrew-cask/pull/109359 renaming formula from adoptopenjdk to temurin.

How about other versions of brew cask formulas like `adoptopenjdk11` ?
Will be renamed to like `temurin11`?

**Comment by gdams** [comment]
@mtgto the plan is to create new casks in the homebrew-cask-versions repo to handle the remaining versions (`temurin8`, `temurin11` etc)

**Comment by mtgto** [comment]
@gdams Thanks! I'll wait it releases.
