### ISSUE TITLE
Support for OpenJDK from Adoptium

### ISSUE THREAD

**Issue by ssaring** [AdoptOpenJDK/homebrew-openjdk#537]
Hi, 

will this cask project support the installation of OpenJDK from the new Adoptium project ( https://adoptium.net/ )? Or is there another cask for that?

Bye, Stefan

**Comment by chesskuo** [comment]
The same question.

Does any way get latest build?

thanks

**Comment by gdams** [comment]
Hi both, this repo will be archived soon. All Eclipse Temurin builds will be provided directly from the Homebrew project.

To download the latest version (16)

```bash
brew install --cask temurin
```

to install other versions:

```bash
brew tap homebrew/cask-versions
brew install --cask temurin8
```

**Comment by ssaring** [comment]
Thanks for clarification! Just tried to install the temurin package - works great.
