### ISSUE TITLE
OpenJDK 17?

### ISSUE THREAD

**Issue by EduardoAraujoB** [AdoptOpenJDK/homebrew-openjdk#542]
# Problem

So, it seems that openjdk 17 was already released and its a problem for me to not have this version here because this version does support to apple silicon macbooks, with the others versions I can not compile without Rosetta 2

# Useful Links

https://openjdk.java.net/projects/jdk/17/

https://adoptium.net/releases.html?variant=openjdk17&jvmVariant=hotspot

**Comment by karianna** [comment]
https://adoptium.net/releases.html and filter for macOS and aarch64 and you'll get a native binary for M1

**Comment by EduardoAraujoB** [comment]
lol, I was talking about having the OpenJDK supported to install via homebrew and not manually, I have the binary and I also linked it in the issue description

**Comment by thomas-gogox** [comment]
Workaround by downloading the JDK 17 and put into path `/Library/Java/JavaVirtualMachines/adoptopenjdk-17.jdk`
Then in terminal  run `jdk 17`
It will work @EduardoAraujoB

**Comment by mthuong** [comment]
Workaround by downloading the JDK 17 and put into path `/Library/Java/JavaVirtualMachines/adoptopenjdk-17.jdk`
Then in terminal run `jdk 17`
It will work @EduardoAraujoB

**Comment by karianna** [comment]
@EduardoAraujoB Load the cask temurin17 to get this version.
