### ISSUE TITLE
Homebrew openjdk install issue

### ISSUE THREAD

**Issue by IshanRattan** [AdoptOpenJDK/homebrew-openjdk#545]
==> Downloading https://hg.openjdk.java.net/jdk-updates/jdk11u/archive/jdk-11.0.
==> Downloading from https://hg.openjdk.org/jdk-updates/jdk11u/archive/jdk-11.0.
                                                #     #  -=#=-  #             
Error: SHA256 mismatch
Expected: 0f35778a120da24dff1f752d128029d87448777a6ab9401c7cf5bc875f127d80
  Actual: c30e0bf48418d9e5b63ad991351f61d4020e6e52bfca9aa5c3557f6a9a90dcdc
    File: /Users/user/Library/Caches/Homebrew/downloads/841adb42e2976e35af75bb87be6dd9c56fe0d4d29a499e4b731d245f4c476626--jdk11u-jdk-11.0.9-ga.tar.bz2
To retry an incomplete download, remove the file above.

**Comment by karianna** [comment]
These are deprecated, please use Eclipse Temurin binaries from adoptium.net, see github.com/adoptium also

**Comment by IshanRattan** [comment]
Tha

> These are deprecated, please use Eclipse Temurin binaries from adoptium.net, see github.com/adoptium also

Thanks alot! I am trying to find a fix for version jdk-15.0.1. Eclipse Temurin binaries don't have jdk-15.0.1. I am trying to install scala using homebrew and it gets stuck here as shown below:

==> Downloading https://hg.openjdk.java.net/jdk-updates/jdk15u/archive/jdk-15.0.1-ga.tar.bz2
Already downloaded: /Users/ishanrattan/Library/Caches/Homebrew/downloads/336948b1d9a8eba79fadf26569f4af0cb2fe147fde214fc9d9bf6b66f2f927d2--jdk15u-jdk-15.0.1-ga.tar.bz2
Error: SHA256 mismatch
Expected: 9c5be662f5b166b5c82c27de29b71f867cff3ff4570f4c8fa646490c4529135a
  Actual: 42942d2ff1f775a0c6fb2739ea1e18a28834e98c752395d535587d5b6462abef
    File: /Users/user/Library/Caches/Homebrew/downloads/336948b1d9a8eba79fadf26569f4af0cb2fe147fde214fc9d9bf6b66f2f927d2--jdk15u-jdk-15.0.1-ga.tar.bz2
To retry an incomplete download, remove the file above.

**Comment by karianna** [comment]
JDK 15 is no longer supported, try 17.0.7 LTS or 20
