### ISSUE TITLE
 adoptopenjdk/openjdk warming

### ISSUE THREAD

**Issue by yuan-xiao-song** [AdoptOpenJDK/homebrew-openjdk#548]
Warning: Calling the `appcast` stanza is deprecated! Use the `livecheck` stanza instead.
Please report this issue to the adoptopenjdk/openjdk tap (not Homebrew/brew or Homebrew/homebrew-core), or even better, submit a PR to fix it:
  /opt/homebrew/Homebrew/Library/Taps/adoptopenjdk/homebrew-openjdk/Casks/adoptopenjdk8.rb:9

Warning: Calling the `appcast` stanza is deprecated! Use the `livecheck` stanza instead.
Please report this issue to the adoptopenjdk/openjdk tap (not Homebrew/brew or Homebrew/homebrew-core), or even better, submit a PR to fix it:
  /opt/homebrew/Homebrew/Library/Taps/adoptopenjdk/homebrew-openjdk/Casks/adoptopenjdk14.rb:8

**Comment by gdams** [comment]
@yuan-xiao-song please migrate to using the `temurin` homebrew casks: https://adoptium.net/installation/
