### ISSUE TITLE
reporting WARNING: `appcast` stanza is deprecated! --> use `livecheck` stanza instead

### ISSUE THREAD

**Issue by peta3000** [AdoptOpenJDK/homebrew-openjdk#549]
Hi, while running `brew update` I got the fallowing warning message, which I'd like to report.

`Warning: Calling the `appcast` stanza is deprecated! Use the `livecheck` stanza instead.
Please report this issue to the adoptopenjdk/openjdk tap (not Homebrew/brew or Homebrew/homebrew-core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/adoptopenjdk/homebrew-openjdk/Casks/adoptopenjdk11.rb:9`
  
 In case this issue-tracker is the false place to post, please feel free to forward it to the right one.
 
 Cheers
 
 p

**Comment by karianna** [comment]
@peta3000 the AdoptOpenJDK installers are no longer supported.  You need to migrate to using the temurin installers from https://adoptium.net/en-GB/
