### ISSUE TITLE
Calling the `appcast` stanza is deprecated! 

### ISSUE THREAD

**Issue by tri5m** [AdoptOpenJDK/homebrew-openjdk#550]
Warning: Calling the `appcast` stanza is deprecated! Use the `livecheck` stanza instead.
Please report this issue to the adoptopenjdk/openjdk tap (not Homebrew/brew or Homebrew/homebrew-core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/adoptopenjdk/homebrew-openjdk/Casks/adoptopenjdk11.rb:9

**Comment by karianna** [comment]
please use casks from adoptium.net instead AdoptOpenJDK is no longer supported
