### ISSUE TITLE
Calling the `appcast` stanza is deprecated! Use the `livecheck` stanza instead.

### ISSUE THREAD

**Issue by crazierGo** [AdoptOpenJDK/homebrew-openjdk#558]
computer : mac m1 
exec  : `brew install etcd`

/opt/homebrew/Library/Taps/adoptopenjdk/homebrew-openjdk/Casks/adoptopenjdk8.rb:9

**Comment by aosen-xiong** [comment]
same here!

**Comment by karianna** [comment]
AdoptOpenjdk is deprecated, please move to Temurin binaries from adoptium.net (Homebrew instructions are there).
