### ISSUE TITLE
adoptopenjdk-jre

### ISSUE THREAD

**Issue by Aarifee** [AdoptOpenJDK/homebrew-openjdk#561]
I cannot understand why I have this error message : 
Warning: Some installed casks are deprecated or disabled. You should find replacements for the following casks: adoptopenjdk. And also this error message when I want to install (brew install --cask adoptopenjdk14) : 
Warning: Cask 'adoptopenjdk14' is unreadable: wrong number of arguments (given 1, expected 0) ==> Searching for similarly named casks...
Error: Cask 'adoptopenjdk14' is unreadable: wrong number of arguments (given 1, expected 0)

**Comment by karianna** [comment]
adoptopenjdk is deprecated and replaced by Eclipse Temurin binaries at adoptium.net - recommend you delete these old casks and install temurin instead
