### ISSUE TITLE
OpenJDK 8 install fails at 'brew link'

### ISSUE THREAD

**Issue by tinca** [AdoptOpenJDK/homebrew-openjdk#6]
Here is what I get on installing jdk 8.

Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink include/classfile_constants.h
/usr/local/include is not writable.

You can try again using:
  brew link adoptopenjdk-openjdk8
==> Summary
🍺  /usr/local/Cellar/adoptopenjdk-openjdk8/jdk8u172-b11: 577 files, 170.4MB, built in 27 seconds
$ brew install adoptopenjdk-openjdk8
Warning: adoptopenjdk/openjdk/adoptopenjdk-openjdk8 jdk8u172-b11 is already installed, it's just not linked
You can use `brew link adoptopenjdk-openjdk8` to link this version.
$ brew link adoptopenjdk-openjdk8
Linking /usr/local/Cellar/adoptopenjdk-openjdk8/jdk8u172-b11... 
Error: Could not symlink include/classfile_constants.h
/usr/local/include is not writable.

How to make this link?

Thank you for your work!!

**Comment by tinca** [comment]
Followed advices from here:
https://stackoverflow.com/questions/26647412/homebrew-could-not-symlink-usr-local-bin-is-not-writable
Needed to create 'include' and 'lib' dirs, set their owner to my user (this is sufficient because I am the only user) then link worked.

**Comment by ches** [comment]
This seems likely to be a Homebrew issue or a system that's broken from Homebrew's perspective, I'd assume `brew doctor` might complain about it. Formulae I'm looking at that link into `${brew --prefix}/include` don't take explicit steps to create these directories or ensure they exist.

**Comment by karianna** [comment]
Closing as it appears to be a Homebrew / System issue
