### ISSUE TITLE
Add VonUniGE to installer team

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/homebrew-openjdk#60]
I would like to nominate @VonUniGE to join the installer team. He has submitted updates/fixes to our homebrew casks and it would be great to get him merge/review permissions.

@VonUniGE are you happy to join?
@AdoptOpenJDK/build any objections?

**Comment by VonUniGE** [comment]
Thank you for your trust.
Yes, I would be happy to be part of this project. Having an open and reproducible build for the OpenJDK is important for me and for the projects I rely on.

**Comment by gdams** [comment]
I'll leave this open for another day and then onboard you if nobody objects

**Comment by gdams** [comment]
@VonUniGE are you on slack? let's get you onboarded!

**Comment by VonUniGE** [comment]
@gdams Yes, I'm on slack now.

**Comment by VonUniGE** [comment]
I'm on board. Thank you.
