### ISSUE TITLE
Cask for JDK11 has a version string inconsistent with other JDKs

### ISSUE THREAD

**Issue by Okeanos** [AdoptOpenJDK/homebrew-openjdk#77]
I was looking at the different cask files and noticed that all of the JDK11 files use the pattern `11.x.y,z` as versioning pattern and then make use of the `#{version.before_comma}` variable to create directories etc. where the JDK lives.
All the other JDK versions provided here and all the other Unix flavours I know of only denote the major version in the path, e.g. `10,0.2:13`. In some cases multiple aliases are symlinked for common path variants.
From a developer perspective only using the major version in the path is also preferable because IDEs and tools such as maven (with [toolchains](https://maven.apache.org/guides/mini/guide-using-toolchains.html) for example) usually don't expect the JDK/JRE path to change on a patch level basis.

Additionally, the cask files for OpenJDK 11 only name themselves `AdoptOpenJDK` whereas all the others also put the major version number into the name such as `AdoptOpenJDK  10`.

**Comment by woj-tek** [comment]
I think similar issue happens with `adoptopenjdk` cask (which currently installs [`adoptopenjdk14`](https://github.com/AdoptOpenJDK/homebrew-openjdk/blob/master/Casks/adoptopenjdk14.rb):
```
==> Verifying SHA-256 checksum for Cask 'adoptopenjdk'.
==> Backing Generic Artifact 'adoptopenjdk-14.jdk' up to '/usr/local/Caskroom/adoptopenjdk/14,36/jdk-14+36'.
==> Removing Generic Artifact '/Library/Java/JavaVirtualMachines/adoptopenjdk-14.jdk'.
==> Moving Generic Artifact 'jdk-14.0.1+7' to '/Library/Java/JavaVirtualMachines/adoptopenjdk-14.0.1.jdk'.
````

So it changed path from `adoptopenjdk-14.jdk` to `adoptopenjdk-14.0.1.jdk` and this isn't preferable as pointed out:
> From a developer perspective only using the major version in the path is also preferable because IDEs and tools such as maven (with toolchains for example) usually don't expect the JDK/JRE path to change on a patch level basis.

Interestingly path for `adoptopenjdk-11.jdk` remained the same.

**Comment by aahlenst** [comment]
@woj-tek The adoptopenjdk cask isn't maintained here, but over at https://github.com/Homebrew/homebrew-cask. Please open a ticket there.

**Comment by woj-tek** [comment]
Thanks, reported here https://github.com/Homebrew/homebrew-cask/issues/81889
