### ISSUE TITLE
Offering a JDK12 nightly cask

### ISSUE THREAD

**Issue by Okeanos** [AdoptOpenJDK/homebrew-openjdk#85]
Would it make sense to offer a JDK12 nightly cask (similar to the [Firefox Nightly](https://github.com/Homebrew/homebrew-cask-versions/blob/master/Casks/firefox-nightly.rb) one in the [Homebrew/homebrew-cask-versions](https://github.com/Homebrew/homebrew-cask-versions) repository or other `-nightly` casks)?

JDK12 is the next major version and actively being developed, having an easy way to stay up to date with the [ongoing releases](https://github.com/AdoptOpenJDK/openjdk12-binaries/releases), e.g. by having a nightly cask, would be an interesting proposition I think is worth investigating.

Interestingly the adoptopenjdk.net website makes no mention of JDK12 on the homepage and also offers no nightly downloads if that is a factor in what should be offered via casks.

There is a `java-beta` cask (see [Homebrew/homebrew-cask-versions/java-beta.rb](https://github.com/Homebrew/homebrew-cask-versions/blob/master/Casks/java-beta.rb)) but that appears not to use (Adopt)OpenJDK binaries and also is a fixed version (currently `12,33`) while at the same time not disclosing this in the label (`OpenJDK Early Access Java Development Kit`) and cask name (`java-beta`).

**Comment by karianna** [comment]
I'm OK with this as its the version that's about to be the next release version.  We've also got a PR on the website for these appearing there.

**Comment by gdams** [comment]
how would we update the cask? my main concern is the maintenance burden unless we could automate it?

**Comment by karianna** [comment]
12 has been released
