### ISSUE TITLE
Getting brew install to appear in `/usr/libexec/java_home`

### ISSUE THREAD

**Issue by jamesmstone** [AdoptOpenJDK/homebrew-openjdk#9]
I performed a `brew install adoptopenjdk-openjdk10` and it appears to have installed correctly in `/usr/local/Cellar/adoptopenjdk-openjdk10/jdk-10.0.1+10` 

Can you please help me have it be detected by `/usr/libexec/java_home`, at present `/usr/libexec/java_home -v` doesn't list it

**Comment by chaines27** [comment]
I got this working yesterday and wanted to share how I did this manually. I'm going to see if I can submit a PR to fix this in the.  You can follow my instructions here https://gist.github.com/chaines27/7f9a91237e79e6b4b28899b96d74986f

**Comment by karianna** [comment]
PR would be awesome.

**Comment by nfrankel** [comment]
@chaines27 thanks for the documentation
However, it would be awesome if it was not necessary to uninstall any Oracle JDK

**Comment by chaines27** [comment]
@nfrankel oh sorry so let me remove that, I don't believe that is necessary. I was trying to completely switch over and wanted to make sure that no Oracle Java existed on my system. With this approach both should be able to co-exist.

**Comment by geowarin** [comment]
FYI, here is how zulu does this:

https://github.com/Homebrew/homebrew-cask-versions/blob/master/Casks/zulu8.rb

**Comment by karianna** [comment]
@chaines27 Are you able to create a PR from your Gist?

**Comment by tristan957** [comment]
Let me see what I can do to create a PR. Bored at work

**Comment by alexejk** [comment]
From what I've gathered - for this to work properly it has to be a Cask and not a formula to correctly run sudo commands - which will allow you to link in `/Library/Java/JavaVirtualMachines`.

**Comment by breun** [comment]
https://blog.adoptopenjdk.net/2018/10/macos-binary-changes

**Comment by karianna** [comment]
I'm going to prematurely close this as - the release should be out in 3-4 hours.

**Comment by gdams** [comment]
The new brew casks that I'm writing will fix this!

**Comment by jshier** [comment]
@gdams Any chance of casks for older OpenJDKs? Anything past 8 isn't compatible with Android tools.
