### ISSUE TITLE
OpenJ9 latest 

### ISSUE THREAD

**Issue by hrstoyanov** [AdoptOpenJDK/homebrew-openjdk#94]
Thank you very much for implementing BREW deployment of AdoptOpenJDK!

Can you, please, implement tracking of the latest OpenJ9, without explicitly specifying jdk version, similar to how you did it for OpenJDK:

```
brew cask install adoptopenjdk
```

I guess, it would be something like:

```
brew cask install adoptopenjdk-openj9
```

While at that, can you also provide large/small heap differentiation across all OpenJ9 versions?

**Comment by VonUniGE** [comment]
The cask [adoptopenjdk](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/adoptopenjdk.rb) is defined in the [homebrew-cask](https://github.com/Homebrew/homebrew-cask) repository. 

We can define in this repository, an adoptopenjdk-openj9 link pointing to the latest version.

@karianna is it ok for you?

**Comment by karianna** [comment]
I'm OK with that but I'll defer to @gdams on brew expertise.

**Comment by karianna** [comment]
@hrstoyanov The Large Heap PR has landed, so you can pick that up now (see the README)

**Comment by hrstoyanov** [comment]
@karianna thanks a lot!

**Comment by gdams** [comment]
yeah I'm happy with an openj9 cask sitting in https://github.com/Homebrew/homebrew-cask.

**Comment by karianna** [comment]
@VonUniGE Please go ahead and make the change!

**Comment by gdams** [comment]
@VonUniGE did this ever happen?

**Comment by VonUniGE** [comment]
I've started a PR on https://github.com/Homebrew/homebrew-cask, but when reviewing the check list I saw:
> Checked the cask was not already refused.

I saw this PR: https://github.com/Homebrew/homebrew-cask/pull/53976

And, it seems that the main maintainer has already made his opinion:
> Closing, all AdoptOpenJDK casks apart from adoptopenjdk will live in the
https://github.com/AdoptOpenJDK/homebrew-openjdk tap.

**Comment by karianna** [comment]
@gdams you'll need to make a call on this I think.
